# Generated by Django 5.1 on 2025-08-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('pokemon_center', 'Pokemon Center'), ('safari_park', 'Safari Park')], default='trainer', max_length=20),
        ),
    ]
