# Generated by Django 5.1 on 2025-08-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
