# Generated by Django 5.1 on 2025-08-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='items_needed',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='pokemon',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
