# Generated by Django 5.1 on 2025-09-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_fundraiser_items_needed_fundraiser_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fundraisers', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_pledges', models.IntegerField(default=0)),
                ('total_amount_pledged', models.IntegerField(default=0)),
                ('successful_fundraisers', models.IntegerField(default=0)),
                ('average_pledge_amount', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Statistics',
            },
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
