# Generated by Django 5.1 on 2025-09-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_sitestats_alter_fundraiser_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitestats',
            old_name='successful_fundraisers',
            new_name='total_pokemon_helped',
        ),
        migrations.RemoveField(
            model_name='sitestats',
            name='average_pledge_amount',
        ),
    ]
