# Generated by Django 5.1 on 2025-10-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0005_rename_successful_fundraisers_sitestats_total_pokemon_helped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
