# Generated by Django 5.1 on 2025-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0006_fundraiser_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='items_needed',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
