# Generated by Django 5.1 on 2025-10-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0007_alter_fundraiser_items_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
