# Generated by Django 5.1 on 2025-11-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0008_alter_pledge_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
